//! Proxy metrics: cheap atomic counters rendered in the Prometheus text
//! exposition format on an optional plain-HTTP endpoint (Step 28).

use std::sync::Arc;
use std::sync::atomic::{AtomicU64, Ordering};

use tokio::io::{AsyncReadExt, AsyncWriteExt};

/// Counters incremented on the data and control planes.
///
/// All counters are monotonically increasing; gauges (active sessions) are
/// read from their owning structures at render time.
#[derive(Debug, Default)]
pub struct Metrics {
    pub sessions_total: AtomicU64,
    pub auth_failures_total: AtomicU64,
    pub packets_hairpin_total: AtomicU64,
    pub packets_tun_out_total: AtomicU64,
    pub packets_to_client_total: AtomicU64,
    pub packets_dropped_total: AtomicU64,
    pub packets_rate_limited_total: AtomicU64,
    pub icmp_errors_sent_total: AtomicU64,
    pub bytes_from_client_total: AtomicU64,
    pub bytes_to_client_total: AtomicU64,
}

impl Metrics {
    pub fn incr(counter: &AtomicU64) {
        counter.fetch_add(1, Ordering::Relaxed);
    }

    pub fn add(counter: &AtomicU64, n: u64) {
        counter.fetch_add(n, Ordering::Relaxed);
    }

    /// Render in Prometheus text exposition format.
    pub fn render(&self, sessions_active: usize) -> String {
        let mut out = String::with_capacity(1024);
        let mut counter = |name: &str, help: &str, value: u64| {
            out.push_str(&format!(
                "# HELP straw_{name} {help}\n# TYPE straw_{name} counter\nstraw_{name} {value}\n"
            ));
        };
        counter(
            "sessions_total",
            "Tunnel sessions established",
            self.sessions_total.load(Ordering::Relaxed),
        );
        counter(
            "auth_failures_total",
            "Rejected authentication attempts",
            self.auth_failures_total.load(Ordering::Relaxed),
        );
        counter(
            "packets_hairpin_total",
            "Packets forwarded client-to-client",
            self.packets_hairpin_total.load(Ordering::Relaxed),
        );
        counter(
            "packets_tun_out_total",
            "Packets forwarded to the TUN device",
            self.packets_tun_out_total.load(Ordering::Relaxed),
        );
        counter(
            "packets_to_client_total",
            "Packets delivered toward clients",
            self.packets_to_client_total.load(Ordering::Relaxed),
        );
        counter(
            "packets_dropped_total",
            "Packets dropped by validation or routing",
            self.packets_dropped_total.load(Ordering::Relaxed),
        );
        counter(
            "packets_rate_limited_total",
            "Packets dropped by per-session rate limits",
            self.packets_rate_limited_total.load(Ordering::Relaxed),
        );
        counter(
            "icmp_errors_sent_total",
            "ICMP errors generated by the proxy",
            self.icmp_errors_sent_total.load(Ordering::Relaxed),
        );
        counter(
            "bytes_from_client_total",
            "Bytes received from clients over tunnels",
            self.bytes_from_client_total.load(Ordering::Relaxed),
        );
        counter(
            "bytes_to_client_total",
            "Bytes sent toward clients over tunnels",
            self.bytes_to_client_total.load(Ordering::Relaxed),
        );
        out.push_str(&format!(
            "# HELP straw_sessions_active Currently active tunnel sessions\n\
             # TYPE straw_sessions_active gauge\nstraw_sessions_active {sessions_active}\n"
        ));
        out
    }
}

/// Serve `GET /metrics` over plain HTTP/1.1. Deliberately minimal — no
/// routing, no TLS; bind it to localhost or a management network.
pub async fn serve_metrics(
    listener: tokio::net::TcpListener,
    ctx: Arc<crate::server::ProxyContext>,
) {
    loop {
        let Ok((mut socket, _)) = listener.accept().await else {
            return;
        };
        let ctx = ctx.clone();
        tokio::spawn(async move {
            // Read (and discard) the request head.
            let mut buf = [0u8; 1024];
            let _ = socket.read(&mut buf).await;

            let body = ctx.metrics.render(ctx.sessions.len());
            let response = format!(
                "HTTP/1.1 200 OK\r\ncontent-type: text/plain; version=0.0.4\r\n\
                 content-length: {}\r\nconnection: close\r\n\r\n{}",
                body.len(),
                body
            );
            let _ = socket.write_all(response.as_bytes()).await;
            let _ = socket.shutdown().await;
        });
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_is_valid_exposition_format() {
        let m = Metrics::default();
        Metrics::incr(&m.sessions_total);
        Metrics::add(&m.bytes_from_client_total, 1500);

        let text = m.render(3);
        assert!(text.contains("straw_sessions_total 1\n"));
        assert!(text.contains("straw_bytes_from_client_total 1500\n"));
        assert!(text.contains("straw_sessions_active 3\n"));
        // Every metric line has HELP and TYPE.
        let metrics = text.lines().filter(|l| !l.starts_with('#')).count();
        let helps = text.lines().filter(|l| l.starts_with("# HELP")).count();
        let types = text.lines().filter(|l| l.starts_with("# TYPE")).count();
        assert_eq!(metrics, helps);
        assert_eq!(metrics, types);
    }
}
